### ISSUE TITLE
Multiple clicks on donate button cause crash

### ISSUE THREAD

**Issue by soenkegissel** [PrivacyApps/donations#37]
Fast clicks on donate button cause crash. Happened multiple times in production already.
See screenshot:
![donate](https://user-images.githubusercontent.com/13346316/36962865-77dd48ac-2051-11e8-8b6a-43d62b7183a1.png)

**Comment by dschuermann** [comment]
duplicate of https://github.com/PrivacyApps/donations/issues/29

If you have a fix please comment there.
