### ISSUE TITLE
IABHelper not setup

### ISSUE THREAD

**Issue by Javinator9889** [PrivacyApps/donations#39]
Recently I commented in the issue #15 because this error is happening again.

I managed to solve it by doing this trick, but the latest version of the lib was not managing it:
(as the code is a bit longer, I will add a PasteBin for better visualization):

--> https://pastebin.com/Wda6FwPz

**Comment by dschuermann** [comment]
Can this be fixed in the library? Can you do a pull request please?

**Comment by Javinator9889** [comment]
Created Pull Request (#40) with a possible solution for this issue (at the commit 30b1c20)
